function uniq(arr) {
  return Array.from(new Set((arr || []).filter(Boolean)));
}

function titleCase(s) {
  return (s || "")
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export function generateAiResumeFromProfile(resume) {
  const skills = uniq(resume.skills).slice(0, 14);
  const topSkill = skills[0] || "Software Development";

  const companyHint = resume.experiences?.[0]?.company ? ` at ${resume.experiences[0].company}` : "";
  const headline = resume.headline ? resume.headline : `${topSkill} Professional`;

  const summary =
    `Profile-driven resume generated by ConnectiFy AI.\n\n` +
    `${resume.name} — ${headline}. ` +
    `Focused on ${skills.slice(0, 4).join(", ") || topSkill}.` +
    `${companyHint ? ` Recent experience${companyHint}.` : ""} ` +
    `Strengths: ${skills.slice(0, 6).join(", ") || topSkill}.`;

  // Light “AI polish”: rewrite experience descriptions into short bullet-like lines
  const experiences = (resume.experiences || []).map((e) => {
    const role = e.title || e.role || "Role";
    const company = e.company || "Company";
    const duration = e.duration || "";
    const base = e.description || e.headline || "";
    const polished = base
      ? base.replace(/\s+/g, " ").trim()
      : `Worked as ${titleCase(role)} at ${company}.`;

    return {
      ...e,
      title: role,
      company,
      duration,
      description: polished,
    };
  });

  return {
    ...resume,
    summary,
    skills,
    experiences,
  };
}


